### ISSUE TITLE
include records with set start or end date

### ISSUE THREAD

**Issue by jonakieling** [einpraegsam/migration#10]
Hi there,

we noticed that only hidden restriction are explicitly removed when exporting data. This leads to missing prepared content. Some of our editors create content with a start date in the future.

Is this use-case generall enough to include directly or maybe as a configuration? I'll provide a PR for the simple hard-coded version.

Kind regards,
Jona

**Comment by einpraegsam** [comment]
Thx for the PR. I just merged it.
