### ISSUE TITLE
Undefined array key "uid" in ImportCommand

### ISSUE THREAD

**Issue by chwessalowski** [einpraegsam/migration#16]
Error when executing the ImportCommand:
PHP Warning: Undefined array key "uid" (Errorcode 1)

Versions:
Extension: 10.0.0
TYPO3: 11.5.23
PHP: 8.1

**Comment by einpraegsam** [comment]
Please give me some more information: The complete error message or the line were the error happens would be helpful

**Comment by chwessalowski** [comment]
Example CLI import: ./vendor/bin/typo3cms migration:import /path-to-json/my-json-import.json 3
Warning: Undefined array key 3 (Errorcode 1)

Looks like there is a problem with uid=3 although it exists. 
Where exactly this occurs in the import script I can not tell. Sorry.

Thanks a lot for your help. 
P.S. By the way migration:migrate works like a charm in TYPO3 version 11.5.23

**Comment by einpraegsam** [comment]
Thx, can you please add a `-vvv` to the command - so:
`./vendor/bin/typo3cms migration:import /path-to-json/my-json-import.json 3 -vvv`
Maybe this gives some more information. I can't reproduce this issue and I have no clue where to start the search :)

**Comment by chwessalowski** [comment]
Unfortunately the -vvv option does not show more information but I tracked it down to: protected function prepareProperties(xxx).

Maybe also good to know for you the CLI:" ./vendor/bin/typo3cms migration:migrate --configuration EXT:migration_wsl_extend/Configuration/Importer.php --key some_key" only worked with my setup after set declare(strict_types=0); in /typo3conf/ext/migration/Classes/Migration/Importer/AbstractImporter.php 

.. and again; thanks a lot for your help.

**Comment by einpraegsam** [comment]
Thx for feedback, that helps a lot.
Can you please try to change line 429 in \In2code\Migration\Port\Import::prepareProperties to this:
```
if (array_key_exists('uid', $properties)) {
    unset($properties['uid']);
}
```
And test again?

**Comment by chwessalowski** [comment]
First test did not succeed but I will elaborate further after the weekend and report. 
Thanks so much for your support.

**Comment by chwessalowski** [comment]
Still the same error after importing with this CLI: ./vendor/bin/typo3cms migration:import /var/path-to-json/demoseiten-64.json 3 -vvv
As you see I want to import the tree in PID=3. 
Error is: Warning: Undefined array key 3 (Errorcode 1)

In my import JSON the first few lines are:
	"records": {
		"pages": [
			{
				"uid": 64,
				"pid": 1,
				"t3ver_oid": 0,
				"t3ver_wsid": 0,

If I debug $properties in \In2code\Migration\Port\Import::prepareProperties:432
array(84 items)
   pid => 3 (integer)
   t3ver_oid => 0 (integer)
   t3ver_wsid => 0 (integer)
   t3ver_state => 0 (integer)

Does that help even more?

**Comment by einpraegsam** [comment]
Sorry, I double checked the code in function prepareProperties() and I'm pretty sure that the change should do it. Are you sure, that you've done the changes on the correct position?
I also pushed a fix to master branch related to prepareProperties().
In my eyes you want to import a table without `uid` field, and PHP 8 throws an error if the array key `uid` should be unsetted anyways.
Nevertheless, if I'm wrong and there is another issue, I would have to test and debug it on my local machine.

**Comment by chwessalowski** [comment]
Sorry I have to give up on that issue. At the moment I do not have the time to elaborate any further. 
But thanks a lot for your help for now.
