### ISSUE TITLE
Missing type casting for PID within SlugPropertyHelper

### ISSUE THREAD

**Issue by ikonplant** [einpraegsam/migration#18]
`[ERROR] Table:xy uidxy pidxy "TYPO3\CMS\Core\DataHandling\SlugHelper::generate(): Argument #2 ($pid) must be of type int, string given, called in /xy/typo3conf/ext/migration/Classes/Migration/PropertyHelpers/SlugPropertyHelper.php on line 58"`

* TYPO3 v11, 
* PHP 8.2, 
* in2code/migration v10.0.0

**Comment by einpraegsam** [comment]
Thx, I just pushed a fix to master branch
