### ISSUE TITLE
Proper quoting for FlexForm Update required

### ISSUE THREAD

**Issue by featdd** [einpraegsam/migration#24]
Hi,

thanks for this awesome extension first.

I encountered some issues while some FlexForm data got updated with the "UpdateXML" Statement.
There seems to be an insufficient quoting of the replaced XML in the [update query here](https://github.com/einpraegsam/migration/blob/f72468754a3811d45e0ea120db541b6807b57e7d/Classes/Port/Service/LinkMappingService.php#L186).

Was this build intentionally? Otherwise we should use `$connection->quote($newValue)` here.

Greetings
Daniel

**Comment by einpraegsam** [comment]
Thx, I just merged your PR
