### ISSUE TITLE
Wrong merging of excluded tables

### ISSUE THREAD

**Issue by akiessling** [einpraegsam/migration#9]
https://github.com/einpraegsam/migration/blob/4f4c0d49727ce58ce17ed1b63d9624d3945302d1/Classes/Port/Import.php#L172

Looks like a similar issue as in #2
https://stitcher.io/blog/what-is-array-plus-in-php - since i never remember what the + does in this context

With the fixed exclude config of 'pages', 'sys_file', 'sys_file_reference', the first 3 excluded tables of the loaded configuration are ignored.

**Comment by einpraegsam** [comment]
Thx, while you can simply merge associative array like:
```
$array3 = $array1 + $array2;
```
this will lead to problems with numeric array (as used in Import.php). I will provide a fix.

**Comment by einpraegsam** [comment]
A just pushed a fix to master. Can you please test the change and give me feedback?

Thx, for your time, Alex

**Comment by akiessling** [comment]
> Thx, while you can simply merge associative arrays (in dimension 1) like:
But the behavior seems to be the same like with numeric keys? With equal associative keys using + the first array wins, while with array_merge the second one overrules the first one.

The patch looks good, thanks for taking care!

**Comment by einpraegsam** [comment]
Thx, I just release 8.0.1 as bugfix release
